### ISSUE TITLE
resumegen project contains LinkedIn API key

### ISSUE THREAD

**Issue by stchris** [WriteCodeEveryday/writecodeeveryday.github.io#7]
You may want to remove this from github: https://github.com/WriteCodeEveryday/writecodeeveryday.github.io/blob/master/projects/resumegen/index.html#L11

**Comment by stchris** [comment]
Refer to this guide, for instance, just to make sure that the api key doesn't remain in the git history: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by WriteCodeEveryday** [comment]
The LinkedIn API key must be exposed for the JS LinkedIn API to work. This key is domain-locked so it is secure to display (it is more of a client ID)                                                                                                                                                                        Source: http://developer.linkedin.com                                                                                                                                                                            From: notifications@github.comSent: April 7, 2017 8:14 AMTo: writecodeeveryday.github.io@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [WriteCodeEveryday/writecodeeveryday.github.io] resumegen project contains LinkedIn API key (#7)  Refer to this guide, for instance, just to make sure that the api key doesn't remain in the git history: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by stchris** [comment]
Alright, thanks for clearing that up!👌
